# We use conda to install cromwell.

language: python

python:
  - 3.6

services:
  - docker

before_install:
  # Install conda
  - export MINICONDA=${HOME}/miniconda
  - export PATH=${MINICONDA}/bin:${PATH}
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p ${MINICONDA}
  - conda config --set always_yes yes
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge

stages:
  - lint
  - test

stage: test

install:
  - conda install --file requirements-test.txt
    # FIXME temporary hack
  - cromwell --version
  - wget https://github.com/rhpvorderman/cromwell/releases/download/51-dev-94aa944/cromwell-51-94aa944-SNAP.jar -O ${HOME}/miniconda/share/cromwell/cromwell.jar
  - cromwell --version

script:
  - travis_wait 30 pytest --keep-workflow-wd-on-fail --tag $TEST tests/

after_failure:
  # Get the last 1000 lines of the cromwell log to catch the error.
  - bash -c 'tail -n 1000 /tmp/pytest_workflow_*/*/log.out'

matrix:
  include:
    - env: TEST=Germline_SingleEnd
    - env: TEST=Germline_PairedEnd
    - env: TEST=Germline_PairedEnd_bwakit
    - env: TEST=Somatic_SingleEnd
    - env: TEST=Somatic_SingleEnd_CNV
      # One of the tools needs to run without the --user flag for docker.
      # This means the workflow directory cannot be removed.
      script: travis_wait 30 pytest --kwd --tag $TEST tests/
    - env: TEST=Somatic_PairedEnd
    - env: TEST=Somatic_PairedEnd_bwakit
    - env: TEST=Germline_GenderAware
    - env: TEST="Womtool validate and submodule up to date"
      stage: lint
      install:
        - conda install cromwell miniwdl wdl-aid
      script: bash scripts/biowdl_lint.sh
      after_failure:
        - echo "Linting failed"
