name: Check tagged submodules

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:

jobs:
  submodule_check:
    runs-on: ubuntu-latest
    name: Check tagged submodules
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
          fetch-depth: 0  # Required to get all history and tags
      - name: check if all submodules are tagged.
        run: >-
          git submodule foreach --recursive
          bash -c '
            if [ "$(git tag -l --points-at HEAD)" == "" ];
            then 
              echo "Untagged submodule found: $PWD. Please make sure all submodules are released.";
              exit 1;
            else 
              echo "contains tag: $(git tag -l --points-at HEAD)";
            fi'
